### ISSUE TITLE
API Endpoint: Fetch Submission History

### ISSUE THREAD

**Issue by eriq-augustine** [eriq-augustine/autograder-server#48]
We can get a specific submission for a user and recent submissions for all users, but we do not have an endpoint for fetching all submissions for a specific user.
Maybe add a parameter to filter by assignment.

**Comment by cfbeard** [comment]
Trying this one!

**Comment by eriq-augustine** [comment]
Complete in 83fc1f781fda18aec7d245d23dc5ffab12e8ed04.
